### PR TITLE
rerender feedstock

### PR DESCRIPTION
**Pull request by ytausch**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

https://github.com/conda-forge/conda-oci-mirror-feedstock/pull/2#issuecomment-2454716599

### CODE REVIEW

**Comment by ytausch** [comment]
@conda-forge-admin please rerender

**Comment by wolfv** [comment]
I think we need to add `setuptools` (ModuleNotFoundError: No module named 'setuptools')

**Comment by ytausch** [comment]
Thank you!

**Comment by ytausch** [comment]
Changing the build number is probably not necessary as there is no build pushed?

**Comment by jaimergp** [comment]
Probably needs some adjustment because the dist metadata shows 0.0.0 as the version:

```
site-packages/conda_oci_mirror-0.0.0.dist-info/INSTALLER
site-packages/conda_oci_mirror-0.0.0.dist-info/LICENSE
site-packages/conda_oci_mirror-0.0.0.dist-info/METADATA
site-packages/conda_oci_mirror-0.0.0.dist-info/RECORD
site-packages/conda_oci_mirror-0.0.0.dist-info/REQUESTED
site-packages/conda_oci_mirror-0.0.0.dist-info/WHEEL
site-packages/conda_oci_mirror-0.0.0.dist-info/direct_url.json
site-packages/conda_oci_mirror-0.0.0.dist-info/entry_points.txt
site-packages/conda_oci_mirror-0.0.0.dist-info/top_level.txt
```

**Comment by ytausch** [comment]
Hmm, this likely has to do with conda-oci-mirror using setuptools-scm and us using the tar.gz archive of the repository, which lacks the git tag info. I tried

```
build:
  script: export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} && {{ PYTHON }} -m pip install . -vv
```

and setting SETUPTOOLS_SCM_PRETEND_VERSION with script_env, but no success.

**Comment by wolfv** [comment]
Weird, this line usually works!

**Comment by wolfv** [comment]
https://github.com/search?q=org%3Aconda-forge%20SETUPTOOLS_SCM_PRETEND_VERSION&type=code

**Comment by pavelzw** [comment]
this is probably because we are not using the pypi version but the version from github?

**Comment by ytausch** [comment]
Adding `setuptools_scm` indeed fixed it...

**Pull request merged**
